### ISSUE TITLE
how to visual the 3D vessel & 3D WSS image

### ISSUE THREAD

**Issue by guomaotianjie** [sukjulian/coronary-mesh-convolution#1]
first than you for your working <Mesh Convolutional Neural Networks for Wall Shear Stress Estimation in 3D Artery Models> and you share the code. now I  have successful  done training, but I don't know how to show the 3D WSS image, thank you very much.

**Comment by guomaotianjie** [comment]
I get 200 predictionxxx.vtp file ,how to visual

**Comment by sukjulian** [comment]
Hi! I suggest you use [ParaView](https://www.paraview.org/).
