### ISSUE TITLE
How to sample

### ISSUE THREAD

**Issue by LiChengChen666** [sukjulian/coronary-mesh-convolution#2]
If I have a mesh consists of ca. 30 million vertices and I want to preserve geometric features, what should I do？

**Comment by sukjulian** [comment]
Hi! If you want to apply GNNs to graphs of 30 million vertices you need large GPUs and I suggest you look into [parallelisation](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html). You even might have to split up meshes across multiple GPUs.
