### ISSUE TITLE
how to  implement CFD simulation with the SimVascular Python shell

### ISSUE THREAD

**Issue by shapera-lab** [sukjulian/coronary-mesh-convolution#4]
It would be very appreciate for you to provide me with some tutorials or examples

**Comment by sukjulian** [comment]
Hi! The SimVascular Python shell is mainly useful for creating the meshes, while the simulation itself is done with the `svpre` and `svsolver` command line tools. See [this](http://simvascular.github.io/docsFlowSolver.html) tutorial from the official SimVascular page.
